### PR TITLE
modal boxes for cards

### PR DESCRIPTION
**Pull request by mcchae-UNO**
updated home.jsp with modal box functionality. 
allows user to click on cards, opening and closing a view with text specific to the card

### CODE REVIEW

**Comment by mcchae-UNO** [comment]
not sure why 
Alexandria/target/m2e-wtp/web-resources/META-INF/maven/Alexandria/Alexandria/pom.properties
is different. it's specified by the .gitignore

**Review by DanielBresnahan1 — COMMENTED** [review]
All of the Servers/ files and folders cannot be in the branch

**Comment by mcchae-UNO** [comment]
I removed the Servers folder from the branch. 
Please correct if incorrect.

**Review by DanielBresnahan1 — APPROVED** [review]
Guuci gang, looks great

**Pull request merged**
